version: '3'

services:
  packer:
    container_name: curtin-labs3
    image: curtin-labs3
    volumes:
      - "./persistence:/CurtinLabBot/persistence"
    tty: false
    entrypoint: /src/start.sh
    restart: unless-stopped